# Generated by Django 6.0.7 on 2026-07-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookHall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roombook',
            options={'ordering': ['booking_date', 'start_time']},
        ),
    ]
