# Generated by Django 6.0 on 2026-02-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(blank=True, unique=True)),
                ('emp_name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('joining_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
