# Generated by Django 6.0.2 on 2026-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_student_saddress_alter_student_sclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='saddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.IntegerField(),
        ),
    ]
