# Generated by Django 6.0 on 2026-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
