# Generated by Django 6.0.2 on 2026-03-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('image', models.CharField(default='https://static.thenounproject.com/png/4595376-200.png', max_length=500)),
            ],
        ),
    ]
