# Generated by Django 6.0.2 on 2026-03-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
