# Generated by Django 6.0.2 on 2026-04-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_app_item_name_0ac13e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
