# Generated by Django 6.0.2 on 2026-04-18 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_item_deleted_at_item_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='app_item_name_0ac13e_idx',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user_name', 'price'], name='app_item_user_na_d8daed_idx'),
        ),
    ]
