# Generated by Django 6.0.2 on 2026-04-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_item_app_item_name_0ac13e_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_availablle',
            new_name='is_available',
        ),
    ]
