# Generated by Django 6.0.2 on 2026-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_is_availablle_item_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(default='https://i.pinimg.com/1200x/2a/a9/b7/2aa9b7ebcb1905e441c6d486dfe3ff9d.jpg', max_length=500),
        ),
    ]
