# Generated by Django 6.0.5 on 2026-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_describ', models.TextField()),
                ('product_image', models.ImageField(default='default.png', upload_to='product_images')),
            ],
        ),
    ]
